-- Spring Batch Meta Tables (MSSQL)
CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NULL,
    JOB_NAME NVARCHAR(100) NOT NULL,
    JOB_KEY NVARCHAR(32) NOT NULL,
    constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
);

CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NULL,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    START_TIME DATETIME DEFAULT NULL,
    END_TIME DATETIME DEFAULT NULL,
    STATUS NVARCHAR(10) NULL,
    EXIT_CODE NVARCHAR(2500) NULL,
    EXIT_MESSAGE NVARCHAR(2500) NULL,
    LAST_UPDATED DATETIME NULL,
    constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
    references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME NVARCHAR(100) NOT NULL,
    PARAMETER_TYPE NVARCHAR(100) NOT NULL,
    PARAMETER_VALUE NVARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STEP_NAME NVARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    START_TIME DATETIME DEFAULT NULL,
    END_TIME DATETIME DEFAULT NULL,
    STATUS NVARCHAR(10) NULL,
    COMMIT_COUNT BIGINT NULL,
    READ_COUNT BIGINT NULL,
    FILTER_COUNT BIGINT NULL,
    WRITE_COUNT BIGINT NULL,
    READ_SKIP_COUNT BIGINT NULL,
    WRITE_SKIP_COUNT BIGINT NULL,
    PROCESS_SKIP_COUNT BIGINT NULL,
    ROLLBACK_COUNT BIGINT NULL,
    EXIT_CODE NVARCHAR(2500) NULL,
    EXIT_MESSAGE NVARCHAR(2500) NULL,
    LAST_UPDATED DATETIME NULL,
    constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT NVARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT NVARCHAR(MAX) NULL,
    constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
    references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT NVARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT NVARCHAR(MAX) NULL,
    constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NO CACHE NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NO CACHE NO CYCLE;
CREATE SEQUENCE BATCH_JOB_INSTANCE_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NO CACHE NO CYCLE;

-- Business Tables
CREATE TABLE ad_click_log (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    campaign_id VARCHAR(50) NOT NULL,
    ad_id VARCHAR(50) NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    event_time DATETIME NOT NULL,
    user_id VARCHAR(100) NOT NULL
);

CREATE TABLE daily_ad_stats (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    stat_date DATE NOT NULL,
    campaign_id VARCHAR(50) NOT NULL,
    ad_id VARCHAR(50) NOT NULL,
    impression_count BIGINT DEFAULT 0,
    click_count BIGINT DEFAULT 0,
    ctr DECIMAL(5,4) DEFAULT 0,
    created_at DATETIME DEFAULT GETDATE(),
    CONSTRAINT uq_daily_ad_stats UNIQUE (stat_date, campaign_id, ad_id)
);
