// AUTO-GENERATED by @dscore/msw - DO NOT EDIT (기본 구조)
// 동적 응답이 필요한 경우 이 파일을 복사 후 수정하세요:
// - 페이지네이션: request.url에서 page, size 파라미터 추출 후 mockData를 slice
// - 검색 필터링: keyword 파라미터로 mockData 필터링
// - 조건부 응답: request body/params에 따라 다른 응답 반환
// - 상태 변경: 외부 변수로 상태를 관리하여 POST/PUT/DELETE 반영
import { http, HttpResponse, delay } from 'msw';

const BASE_URL = (() => {
  // Vite
  if (typeof import.meta !== 'undefined' && import.meta.env?.VITE_API_BASE) return import.meta.env.VITE_API_BASE;
  // Webpack (CRA, Next.js)
  if (typeof process !== 'undefined' && process.env?.REACT_APP_API_BASE) return process.env.REACT_APP_API_BASE;
  if (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_API_BASE) return process.env.NEXT_PUBLIC_API_BASE;
  return '/api';
})();

export const BATCH_HISTORY_HANDLER = [
  http.get(`${BASE_URL}/om/batch-history/histories`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode) {
      return HttpResponse.json(
        { message: 'Error' },
        { status: parseInt(errorCode) }
      );
    }

    await delay(200);
    return HttpResponse.json(
      {
        "data": {
          "result": [
            {
              "jobName": "dailySettlement",
              "jobInstanceId": 1001,
              "jobExecutionId": 1001,
              "startTime": "2026-03-07 02:00:00",
              "endTime": "2026-03-07 02:05:30",
              "status": "COMPLETED",
              "exitCode": "COMPLETED",
              "exitMessage": ""
            },
            {
              "jobName": "dailyReport",
              "jobInstanceId": 1002,
              "jobExecutionId": 1002,
              "startTime": "2026-03-07 06:00:00",
              "endTime": "2026-03-07 06:12:45",
              "status": "COMPLETED",
              "exitCode": "COMPLETED",
              "exitMessage": ""
            },
            {
              "jobName": "cacheRefresh",
              "jobInstanceId": 1003,
              "jobExecutionId": 1003,
              "startTime": "2026-03-06 12:30:00",
              "endTime": "2026-03-06 12:30:15",
              "status": "FAILED",
              "exitCode": "FAILED",
              "exitMessage": "Connection timeout"
            },
            {
              "jobName": "weeklyBackup",
              "jobInstanceId": 1004,
              "jobExecutionId": 1004,
              "startTime": "2026-03-02 03:00:00",
              "endTime": "2026-03-02 03:45:20",
              "status": "COMPLETED",
              "exitCode": "COMPLETED",
              "exitMessage": ""
            }
          ],
          "page": {
            "page": 1,
            "size": 10,
            "totalElements": 4
          }
        }
      },
      { status: 200 }
    );
  }),

  http.get(`${BASE_URL}/om/batch-history/histories/:jobExecutionId`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode === '404') {
      return HttpResponse.json(
        { message: '배치 실행 이력을 찾을 수 없습니다.' },
        { status: 404 }
      );
    }

    return HttpResponse.json(
      {
        "data": {
          "jobName": "dailySettlement",
          "jobInstanceId": 1001,
          "jobExecutionId": 1001,
          "startTime": "2026-03-07 02:00:00",
          "endTime": "2026-03-07 02:05:30",
          "status": "COMPLETED",
          "exitCode": "COMPLETED",
          "exitMessage": "",
          "batchHstStepList": [
            {
              "stepName": "step1-readData",
              "startTime": "2026-03-07 02:00:01",
              "endTime": "2026-03-07 02:02:00",
              "status": "COMPLETED",
              "readCount": 15000,
              "writeCount": 15000,
              "commitCount": 150,
              "rollbackCount": 0,
              "exitCode": "COMPLETED",
              "exitMessage": ""
            },
            {
              "stepName": "step2-processData",
              "startTime": "2026-03-07 02:02:01",
              "endTime": "2026-03-07 02:05:30",
              "status": "COMPLETED",
              "readCount": 15000,
              "writeCount": 14980,
              "commitCount": 150,
              "rollbackCount": 0,
              "exitCode": "COMPLETED",
              "exitMessage": ""
            }
          ],
          "batchHstJobParamList": [
            {
              "parameterName": "run.id",
              "parameterType": "LONG",
              "parameterValue": "1",
              "identifying": "Y"
            }
          ]
        }
      },
      { status: 200 }
    );
  }),

  http.put(`${BASE_URL}/om/batch-history/histories/trigger`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode === '400') {
      return HttpResponse.json(
        { message: '현재 실행 중인 배치가 있습니다.' },
        { status: 400 }
      );
    }

    await delay(500);
    return HttpResponse.json(
      {
        "data": {
          "message": "배치가 재실행되었습니다.",
          "jobExecutionId": 1005
        }
      },
      { status: 200 }
    );
  })
];

export const BATCH_HISTORY_HANDLER_INFO = {
  domain: 'batch_history',
  endpoints: [
    {
      "method": "GET",
      "path": "/om/batch-history/histories"
    },
    {
      "method": "GET",
      "path": "/om/batch-history/histories/:jobExecutionId"
    },
    {
      "method": "PUT",
      "path": "/om/batch-history/histories/trigger"
    }
  ]
};
