// AUTO-GENERATED by @dscore/msw - DO NOT EDIT (기본 구조)
// 동적 응답이 필요한 경우 이 파일을 복사 후 수정하세요:
// - 페이지네이션: request.url에서 page, size 파라미터 추출 후 mockData를 slice
// - 검색 필터링: keyword 파라미터로 mockData 필터링
// - 조건부 응답: request body/params에 따라 다른 응답 반환
// - 상태 변경: 외부 변수로 상태를 관리하여 POST/PUT/DELETE 반영
import { http, HttpResponse, delay } from 'msw';

const BASE_URL = (() => {
  // Vite
  if (typeof import.meta !== 'undefined' && import.meta.env?.VITE_API_BASE) return import.meta.env.VITE_API_BASE;
  // Webpack (CRA, Next.js)
  if (typeof process !== 'undefined' && process.env?.REACT_APP_API_BASE) return process.env.REACT_APP_API_BASE;
  if (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_API_BASE) return process.env.NEXT_PUBLIC_API_BASE;
  return '/api';
})();

export const BATCH_SCHEDULE_HANDLER = [
  http.get(`${BASE_URL}/om/batch-schedule/schedules`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode) {
      return HttpResponse.json(
        { message: 'Error' },
        { status: parseInt(errorCode) }
      );
    }

    await delay(200);
    return HttpResponse.json(
      {
        "data": {
          "result": [
            {
              "jobGroup": "DAILY",
              "jobNm": "dailySettlement",
              "paramSbst": "",
              "useYnNm": "사용",
              "perdSbst": "0 0 2 * * ?",
              "regrNm": "system",
              "regDt": "2025-01-10 09:00:00"
            },
            {
              "jobGroup": "DAILY",
              "jobNm": "dailyReport",
              "paramSbst": "",
              "useYnNm": "사용",
              "perdSbst": "0 0 6 * * ?",
              "regrNm": "system",
              "regDt": "2025-01-10 09:00:00"
            },
            {
              "jobGroup": "WEEKLY",
              "jobNm": "weeklyBackup",
              "paramSbst": "",
              "useYnNm": "사용",
              "perdSbst": "0 0 3 ? * SUN",
              "regrNm": "system",
              "regDt": "2025-02-01 10:00:00"
            },
            {
              "jobGroup": "MONTHLY",
              "jobNm": "monthlyStatistics",
              "paramSbst": "",
              "useYnNm": "사용",
              "perdSbst": "0 0 1 1 * ?",
              "regrNm": "admin001",
              "regDt": "2025-03-01 09:00:00"
            },
            {
              "jobGroup": "DAILY",
              "jobNm": "cacheRefresh",
              "paramSbst": "",
              "useYnNm": "미사용",
              "perdSbst": "0 */30 * * * ?",
              "regrNm": "admin001",
              "regDt": "2025-04-15 14:00:00"
            }
          ],
          "page": {
            "page": 1,
            "size": 10,
            "totalElements": 5
          }
        }
      },
      { status: 200 }
    );
  }),

  http.post(`${BASE_URL}/om/batch-schedule/schedules`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode) {
      return HttpResponse.json(
        { message: 'Error' },
        { status: parseInt(errorCode) }
      );
    }

    return HttpResponse.json(
      {
        "data": {
          "message": "배치 스케줄이 등록되었습니다."
        }
      },
      { status: 200 }
    );
  }),

  http.get(`${BASE_URL}/om/batch-schedule/schedules/:jobGroup/:jobNm`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode === '404') {
      return HttpResponse.json(
        { message: '배치 스케줄을 찾을 수 없습니다.' },
        { status: 404 }
      );
    }

    return HttpResponse.json(
      {
        "data": {
          "jobGroup": "DAILY",
          "jobNm": "dailySettlement",
          "jobDesc": "일일 정산 배치",
          "useYn": "Y",
          "paramSbst": "",
          "perdSbst": "0 0 2 * * ?",
          "regrNm": "system",
          "regDt": "2025-01-10 09:00:00"
        }
      },
      { status: 200 }
    );
  }),

  http.put(`${BASE_URL}/om/batch-schedule/schedules/:jobGroup/:jobNm`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode) {
      return HttpResponse.json(
        { message: 'Error' },
        { status: parseInt(errorCode) }
      );
    }

    return HttpResponse.json(
      {
        "data": {
          "message": "배치 스케줄이 수정되었습니다."
        }
      },
      { status: 200 }
    );
  })
];

export const BATCH_SCHEDULE_HANDLER_INFO = {
  domain: 'batch_schedule',
  endpoints: [
    {
      "method": "GET",
      "path": "/om/batch-schedule/schedules"
    },
    {
      "method": "POST",
      "path": "/om/batch-schedule/schedules"
    },
    {
      "method": "GET",
      "path": "/om/batch-schedule/schedules/:jobGroup/:jobNm"
    },
    {
      "method": "PUT",
      "path": "/om/batch-schedule/schedules/:jobGroup/:jobNm"
    }
  ]
};
