// AUTO-GENERATED by @dscore/msw - DO NOT EDIT (기본 구조)
// 동적 응답이 필요한 경우 이 파일을 복사 후 수정하세요:
// - 페이지네이션: request.url에서 page, size 파라미터 추출 후 mockData를 slice
// - 검색 필터링: keyword 파라미터로 mockData 필터링
// - 조건부 응답: request body/params에 따라 다른 응답 반환
// - 상태 변경: 외부 변수로 상태를 관리하여 POST/PUT/DELETE 반영
import { http, HttpResponse, delay } from 'msw';

const BASE_URL = (() => {
  // Vite
  if (typeof import.meta !== 'undefined' && import.meta.env?.VITE_API_BASE) return import.meta.env.VITE_API_BASE;
  // Webpack (CRA, Next.js)
  if (typeof process !== 'undefined' && process.env?.REACT_APP_API_BASE) return process.env.REACT_APP_API_BASE;
  if (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_API_BASE) return process.env.NEXT_PUBLIC_API_BASE;
  return '/api';
})();

export const COMCD_MGT_HANDLER = [
  http.get(`${BASE_URL}/om/code-mgt/groups`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode) {
      return HttpResponse.json(
        { message: 'Error' },
        { status: parseInt(errorCode) }
      );
    }

    await delay(200);
    return HttpResponse.json(
      {
        "data": {
          "result": [
            {
              "cdGroupId": "USE_YN",
              "cdGroupNm": "사용 여부",
              "cdGroupDesc": "사용 여부 코드 그룹",
              "useYn": "Y",
              "codeCnt": 2,
              "regDt": "2025-01-01 09:00:00"
            },
            {
              "cdGroupId": "GENDER_CD",
              "cdGroupNm": "성별 코드",
              "cdGroupDesc": "성별 구분 코드",
              "useYn": "Y",
              "codeCnt": 2,
              "regDt": "2025-01-01 09:00:00"
            },
            {
              "cdGroupId": "STATUS_CD",
              "cdGroupNm": "상태 코드",
              "cdGroupDesc": "계정/서비스 상태 코드",
              "useYn": "Y",
              "codeCnt": 3,
              "regDt": "2025-01-01 09:00:00"
            },
            {
              "cdGroupId": "HTTP_METHOD_CD",
              "cdGroupNm": "HTTP 메소드",
              "cdGroupDesc": "HTTP 요청 메소드 코드",
              "useYn": "Y",
              "codeCnt": 5,
              "regDt": "2025-01-01 09:00:00"
            },
            {
              "cdGroupId": "SEARCH_CODE_TYPE_CD",
              "cdGroupNm": "검색 유형 코드",
              "cdGroupDesc": "검색 유형 구분 코드",
              "useYn": "Y",
              "codeCnt": 3,
              "regDt": "2025-01-15 10:00:00"
            }
          ],
          "page": {
            "page": 1,
            "size": 10,
            "totalCount": 5,
            "totalPage": 1
          }
        }
      },
      { status: 200 }
    );
  }),

  http.post(`${BASE_URL}/om/code-mgt/groups`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode === '400') {
      return HttpResponse.json(
        { message: '이미 존재하는 코드 그룹 ID입니다.' },
        { status: 400 }
      );
    }

    return HttpResponse.json(
      {
        "data": {
          "message": "코드 그룹이 등록되었습니다."
        }
      },
      { status: 200 }
    );
  }),

  http.get(`${BASE_URL}/om/code-mgt/groups/:cdGroupId`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode === '404') {
      return HttpResponse.json(
        { message: '코드 그룹을 찾을 수 없습니다.' },
        { status: 404 }
      );
    }

    return HttpResponse.json(
      {
        "data": {
          "cdGroupId": "USE_YN",
          "cdGroupNm": "사용 여부",
          "cdGroupDesc": "사용 여부 코드 그룹",
          "useYn": "Y",
          "regDt": "2025-01-01 09:00:00",
          "modDt": "2025-06-15 14:00:00",
          "regId": "system",
          "modId": "admin001"
        }
      },
      { status: 200 }
    );
  }),

  http.put(`${BASE_URL}/om/code-mgt/groups/:cdGroupId`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode) {
      return HttpResponse.json(
        { message: 'Error' },
        { status: parseInt(errorCode) }
      );
    }

    return HttpResponse.json(
      {
        "data": {
          "message": "코드 그룹이 수정되었습니다."
        }
      },
      { status: 200 }
    );
  }),

  http.get(`${BASE_URL}/om/code-mgt/groups/:cdGroupId/codes`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode) {
      return HttpResponse.json(
        { message: 'Error' },
        { status: parseInt(errorCode) }
      );
    }

    const cdGroupId = params.cdGroupId;

    const codesByGroup = {
      BATCH_STATUS: [
        { cdId: "COMPLETED", cdNm: "완료", cdGroupId: "BATCH_STATUS", cdOrd: 1, useYn: "Y", cdDesc: "정상 완료", regDt: "2025-01-01 09:00:00" },
        { cdId: "FAILED", cdNm: "실패", cdGroupId: "BATCH_STATUS", cdOrd: 2, useYn: "Y", cdDesc: "실패", regDt: "2025-01-01 09:00:00" },
        { cdId: "STARTED", cdNm: "실행중", cdGroupId: "BATCH_STATUS", cdOrd: 3, useYn: "Y", cdDesc: "실행 중", regDt: "2025-01-01 09:00:00" },
        { cdId: "STARTING", cdNm: "시작", cdGroupId: "BATCH_STATUS", cdOrd: 4, useYn: "Y", cdDesc: "시작 중", regDt: "2025-01-01 09:00:00" },
        { cdId: "STOPPED", cdNm: "중단", cdGroupId: "BATCH_STATUS", cdOrd: 5, useYn: "Y", cdDesc: "중단됨", regDt: "2025-01-01 09:00:00" },
        { cdId: "UNKNOWN", cdNm: "알수없음", cdGroupId: "BATCH_STATUS", cdOrd: 6, useYn: "Y", cdDesc: "알 수 없음", regDt: "2025-01-01 09:00:00" }
      ],
      BATCH_GROUP_NAME: [
        { cdId: "DAILY", cdNm: "일별", cdGroupId: "BATCH_GROUP_NAME", cdOrd: 1, useYn: "Y", cdDesc: "일별 배치", regDt: "2025-01-01 09:00:00" },
        { cdId: "WEEKLY", cdNm: "주간", cdGroupId: "BATCH_GROUP_NAME", cdOrd: 2, useYn: "Y", cdDesc: "주간 배치", regDt: "2025-01-01 09:00:00" },
        { cdId: "MONTHLY", cdNm: "월간", cdGroupId: "BATCH_GROUP_NAME", cdOrd: 3, useYn: "Y", cdDesc: "월간 배치", regDt: "2025-01-01 09:00:00" }
      ],
      USE_YN: [
        { cdId: "Y", cdNm: "사용", cdGroupId: "USE_YN", cdOrd: 1, useYn: "Y", cdDesc: "사용 상태", regDt: "2025-01-01 09:00:00" },
        { cdId: "N", cdNm: "미사용", cdGroupId: "USE_YN", cdOrd: 2, useYn: "Y", cdDesc: "미사용 상태", regDt: "2025-01-01 09:00:00" }
      ]
    };

    const result = codesByGroup[cdGroupId] ?? codesByGroup.USE_YN;

    return HttpResponse.json(
      {
        "data": {
          "result": result,
          "page": {
            "page": 1,
            "size": 10,
            "totalCount": result.length,
            "totalPage": 1
          }
        }
      },
      { status: 200 }
    );
  }),

  http.post(`${BASE_URL}/om/code-mgt/groups/:cdGroupId/codes`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode) {
      return HttpResponse.json(
        { message: 'Error' },
        { status: parseInt(errorCode) }
      );
    }

    return HttpResponse.json(
      {
        "data": {
          "message": "코드가 등록되었습니다."
        }
      },
      { status: 200 }
    );
  }),

  http.get(`${BASE_URL}/om/code-mgt/groups/:cdGroupId/codes/:cdId`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode === '404') {
      return HttpResponse.json(
        { message: '코드를 찾을 수 없습니다.' },
        { status: 404 }
      );
    }

    return HttpResponse.json(
      {
        "data": {
          "cdId": "Y",
          "cdNm": "사용",
          "cdGroupId": "USE_YN",
          "cdOrd": 1,
          "useYn": "Y",
          "cdDesc": "사용 상태",
          "regDt": "2025-01-01 09:00:00",
          "modDt": "2025-06-15 14:00:00",
          "regId": "system",
          "modId": "admin001"
        }
      },
      { status: 200 }
    );
  }),

  http.put(`${BASE_URL}/om/code-mgt/groups/:cdGroupId/codes/:cdId`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode) {
      return HttpResponse.json(
        { message: 'Error' },
        { status: parseInt(errorCode) }
      );
    }

    return HttpResponse.json(
      {
        "data": {
          "message": "코드가 수정되었습니다."
        }
      },
      { status: 200 }
    );
  }),

  http.get(`${BASE_URL}/system/caches/refresh/:cacheName`, async ({ request, params }) => {
    const url = new URL(request.url);
    const errorCode = url.searchParams.get('error');

    if (errorCode) {
      return HttpResponse.json(
        { message: 'Error' },
        { status: parseInt(errorCode) }
      );
    }

    return HttpResponse.json(
      {
        "data": {
          "message": "캐시가 갱신되었습니다."
        }
      },
      { status: 200 }
    );
  })
];

export const COMCD_MGT_HANDLER_INFO = {
  domain: 'comcd_mgt',
  endpoints: [
    {
      "method": "GET",
      "path": "/om/code-mgt/groups"
    },
    {
      "method": "POST",
      "path": "/om/code-mgt/groups"
    },
    {
      "method": "GET",
      "path": "/om/code-mgt/groups/:cdGroupId"
    },
    {
      "method": "PUT",
      "path": "/om/code-mgt/groups/:cdGroupId"
    },
    {
      "method": "GET",
      "path": "/om/code-mgt/groups/:cdGroupId/codes"
    },
    {
      "method": "POST",
      "path": "/om/code-mgt/groups/:cdGroupId/codes"
    },
    {
      "method": "GET",
      "path": "/om/code-mgt/groups/:cdGroupId/codes/:cdId"
    },
    {
      "method": "PUT",
      "path": "/om/code-mgt/groups/:cdGroupId/codes/:cdId"
    },
    {
      "method": "GET",
      "path": "/system/caches/refresh/:cacheName"
    }
  ]
};
