// AUTO-GENERATED by @dscore/msw - DO NOT EDIT
/**
 * ============================================
 * MSW Worker Setup for Vue 3
 * ============================================
 *
 * 사용 방법 (main.js 또는 main.ts):
 *
 * import { createApp } from 'vue'
 * import App from './App.vue'
 *
 * async function bootstrap() {
 *   if (import.meta.env.DEV) {
 *     const { startMockWorker } = await import('./mocks/mockWorker.js')
 *     await startMockWorker()
 *   }
 *
 *   createApp(App).mount('#app')
 * }
 *
 * bootstrap()
 *
 * ============================================
 */

import { setupWorker } from 'msw/browser';
import { handlers, logRegisteredHandlers } from './handlers.js';

export const worker = setupWorker(...handlers);

export async function startMockWorker() {
  await worker.start({
    onUnhandledRequest: 'bypass',
  });

  logRegisteredHandlers();

  return worker;
}
